apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs-demo
        image: perpusbelajar/app-js:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-service
spec:
  type: NodePort
  selector:
    app: nodejs-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32081
